import type { NextPage } from 'next';
import Head from 'next/head';
// import Image from 'next/image';
import styles from '../styles/Home.module.scss';

const Home: NextPage = () => (
  <div className={styles.container}>
    <Head>
      <title>Credigible</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
      <h1 className={styles.title}>
        Credigible
      </h1>
    </main>
  </div>
);

export default Home;
