#Production
FROM node:16-alpine as builder
WORKDIR /usr/server
COPY server/package*.json ./
RUN npm install
COPY ./server .
RUN npm run build

FROM node:16-alpine as credigible-server-production
WORKDIR /usr/server
COPY server/package*.json ./
RUN npm install --production
COPY --from=builder /usr/server/build ./build

#Have to later put copying of env variables to stage 2

EXPOSE 3000
CMD node build/index.js
