services:
    db:
        image: mariadb:10.7
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: test
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        ports:
            - 3306:3306
    server:
        depends_on:
            - db
        build:
            context: ..
            dockerfile: docker/Dockerfile.server.dev
        image: credigible-server-dev-image
        volumes:
            - ../server:/usr/server
        ports:
            - "4000:4000"

    web:
        build:
            context: ..
            dockerfile: docker/Dockerfile.web.dev
        image: credigible-web-dev-image
        volumes:
            - ../web:/usr/web
        ports:
            - "3000:3000"

volumes:
    db_data: {}
