services:
    server:
        build:
            context: ..
            dockerfile: docker/Dockerfile.server.dev
        image: credigible-server-dev-image
        volumes:
            - ../server:/usr/server
        ports:
            - "4000:4000"

    web:
        build:
            context: ..
            dockerfile: docker/Dockerfile.web.dev
        image: credigible-web-dev-image
        volumes:
            - ../web:/usr/web
        ports:
            - "3000:3000"
